---
title: "Homework5"
author: "Annie Yu"
date: "11/2/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
library(rvest)
library(reshape2)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```
##Problem 1
### Create a tidy dataframe 
```{r}
long_study <- list.files('/Users/annie/Desktop/data science/Homework/homework5/Homework 5/data')  

df_longstudy <- function(x){
   read_df<- read_csv(paste0('/Users/annie/Desktop/data science/Homework/homework5/Homework 5/data/', x))
   read_df
}

output= map(long_study, df_longstudy)
week_results = bind_rows(output)

read_df<-long_study %>% 
  str_replace('.csv', '') 

df<-as.data.frame(read_df) 

longstudy<-
  cbind(df, week_results) %>% 
  gather(key = week, value = value, week_1:week_8) %>% 
  mutate(week = str_replace(week, 'week_', '')) %>% 
  mutate(week = as.numeric(week)) %>% 
  separate(read_df, into = c("arms", "id"),sep = "_") 

  
```

### Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.
```{r}
ggplot(longstudy, aes(x= week, y = value, color=id))+
  facet_grid(~as.factor(arms))+
  geom_line()+
  labs(
    title = "The Difference Between Control Group and Experiment Gruop",
    x = "Weeks",
    y = "Value"
  )+
  viridis::scale_color_viridis(
    discrete = TRUE
  ) + 
  theme(legend.position = "bottom")
  
```



